{% set name = "pyls-black" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e087adca067391a65a577676ea2d62f0a6cb2bf23bf45dbefbbd48c0d2bb8d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - black
    - python-language-server
    - toml

test:
  imports:
    - pyls_black
    - pyls_black.plugin

about:
  home: https://github.com/rupert/pyls-black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Black plugin for the Python Language Server
  dev_url: https://github.com/rupert/pyls-black

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - steff456
